name: "flutterfire_cli_monorepo"
publish_to: none
environment:
  sdk: ">=2.17.0 <3.0.0"

executables:
  flutterfire: flutterfire_dev

dev_dependencies:
  flutterfire_cli:
    path: ./packages/flutterfire_cli
  melos: ^5.3.0
  path: ^1.8.0
  yaml: ^3.1.0

dependency_overrides:
  flutterfire_cli:
    path: ./packages/flutterfire_cli
